name: QEMU ARM64 + SpaceROS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-sgl.yml
    with:
      kas_config: sgl-scarthgap-spaceros-jazzy-2026.07-core-qemuarm64.yml
      hardware_arch: qemuarm64
      build_profile: spaceros
