name: BeagleV-Fire + SpaceROS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-sgl.yml
    with:
      kas_config: sgl-scarthgap-spaceros-jazzy-2026.07-beaglev-fire.yml
      hardware_arch: beaglev-fire
      build_profile: spaceros
